openapi: '3.0.2'
info:
  title: Service Orders Management
  description: This api provides resources to manage service orders register and flow, allowing to keep device history
  version: '1.0'
servers:
  - url: http://{host}/api/{version}
    variables:
      host:
        enum:
          - localhost:8000
          - somvp.herokuapp.com
        default: localhost:8000
        description: The host used for development
      version:
        enum:
          - v1
        default: v1
        description: MVP (minimum viable product) version
security:
  - bearerAuth: []



    




